#You can override this in ~/.gradle/gradle.properties
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
test.heap.max=1g
android.nonTransitiveRClass=true
android.injected.androidTest.leaveApksInstalledAfterRun=true
org.gradle.java.installations.auto-download=true
versionCode=5120

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
